### ISSUE TITLE
couldn't replicate your success! preinstall didn't run

### ISSUE THREAD

**Issue by jaredh159** [slawekkolodziej/netlify-lerna-caching-demo#1]
Hey I spent a while trying to replicate what you did here in my monorepo, and had no luck.

I think I ultimately figured out that my problem seems to be that the `preinstall` lifecycle method was never getting run on netlify.  Did you have any trouble with this?

I have a little bare-bones monorepo test repo where I experiment with things on netlify, and so I added a commit to test the `preinstall` hook: https://github.com/jaredh159/monorepo-test/commit/516a7b0d6591ffee1a451e4a890ffefcecfdc753 -- but no dice, it's not getting called.

Super stumped, and baffled how you got this working.  Any pointers would be _greatly_ appreciated.

**Comment by slawekkolodziej** [comment]
I just run into this issue with my real-world app too 😄

The `preinstall` hook has to be defined in the package.json next to your netlify.toml file. Also, you should use that package's node_modules as your cache dir (my scripts move everything to root-level node_modules).

I already modified the scripts to work with this scenario, will update my demo later on.

**Comment by jaredh159** [comment]
Ahh, yup, that makes sense. Really appreciate the tip. Next time I have energy to take another whack, I'll see if I can get it working.
