### ISSUE TITLE
How does the restore know whether the cache is not out of date?

### ISSUE THREAD

**Issue by JakubKoralewski** [slawekkolodziej/netlify-lerna-caching-demo#4]
Hello!

I'm trying to understand how your amazing solution works 😄 

What I fail to understand is, that it looks to me as if the other packages' node_modules are cached and restored every single time(?), but what happens when the other packages' node_modules get changed? Looks to me like it will always restore the same cache forever? 

Or is this something netlify handles automatically when yarn.lock changes in the root? Since the package-level yarn.locks are empty.

Thanks.

**Comment by slawekkolodziej** [comment]
Yes yarn handles it automatically when root-level yarn.lock changes.

**Comment by JakubKoralewski** [comment]
@slawekkolodziej Wow. That's awesome! Thanks.
